{% set name = "types-cachetools" %}
{% set version = "0.1.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-cachetools-{{ version }}.tar.gz
  sha256: f2727cf379989ba4d081f9ed11ec28c6730adbd120dc0deb2036c5ef69e515e0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/cachetools-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for cachetools
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
