{% set name = "types-cachetools" %}
{% set version = "4.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-cachetools-{{ version }}.tar.gz
  sha256: d9faa19bb2cf818edf763b126e2d076dd6e92ce9e9cd478b4aea705e0216d0cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/cachetools-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for cachetools
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
